# SPDX-License-Identifier: AGPL-3.0-or-later
version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive
    - gocyclo
    - gocognit
    - gocritic
#    - stylecheck
#    - typecheck
    - unparam
    - unconvert
    - misspell
    - errorlint
    - prealloc
    - gosec
    - cyclop
    - dupl
    - forbidigo
    - whitespace
    - nolintlint
    - testpackage
  settings:
    gocyclo:
      min-complexity: 15
    cyclop:
      max-complexity: 15
      package-average: 0.0
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
        - name: receiver-naming
        - name: early-return
        - name: errorf
        - name: error-naming
        - name: package-comments
        - name: indent-error-flow
    forbidigo:
      forbid:
        - pattern: 'fmt\.Print(f|ln)?\('
      exclude-godoc-examples: true
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - gocyclo
          - cyclop
          - dupl
      - path: ^third_party/|^vendor/|^docs/|^\.github/
        linters:
          - gosec
    paths:
      - vendor
      - third_party
      - docs
      - .git
      - .github

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - vendor
      - third_party
      - docs
      - .git
      - .github

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
