# SPDX-License-Identifier: AGPL-3.0-or-later
name: "Feature request"
description: "Suggest a new feature or improvement for flowd."
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature or change you want.
      placeholder: Add support for …
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: When I try to … it’s hard because …
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like flowd to behave? CLI examples or config examples are helpful.
      placeholder: |
        Example:

        flwd ...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches you’ve considered.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else that might help (related tools, prior art, links).
    validations:
      required: false
