name: trivy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '29 4 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@821474463d541e9c67e7c310e6b95c7c6a44e327
        with:
          sarif_file: trivy-results.sarif